openshift/sriov-network-operator

deploy/operator.yaml, manifests/4.2/sriov-network-operator.v0.0.1.clusterserviceversion.yaml
YAML reserved the words "false" and "true" and assumes these are boolean
unless quoted, which makes applying the operator manifest to fail
because of unexpected type of the value attribute.
=> Fixed ENABLE_ADMISSION_CONTROLLER envvar type to string

Dockerfile, Dockerfile.rhel7, Dockerfile.sriov-network-config-daemon, Dockerfile.sriov-network-config-daemon.rhel7, hack/build-go.sh, hack/build-plugins.sh
This is necessary for building on platforms other than amd64.
=> Do not hardcode GOOS/GOARCH

pkg/controller/sriovnetwork/sriovnetwork_controller.go
Instantiate a new client to avoid querying the cache which
won't find any NetAttDef in a different namespace
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
=> Fix update NetAttDefs in different namespaces

pkg/apis/sriovnetwork/v1/helper.go
When numVfs is not set, the device device ID of PF shall be used; otherwise, ID of VF shall be used.
=> Fix the nic selection logic for updating SriovNetworkNodeState

Dockerfile.sriov-network-config-daemon, Dockerfile.sriov-network-config-daemon.rhel7, pkg/plugins/mellanox/mellanox_plugin.go
Fix bug when the link type is IB, because the mlnxNic `singlePort` and `firstPort` bool flags are not updated, the plugin always assume the NIC is 2 ports and the 2nd port should be updated
=> Fix mlnx plugin when linkType is IB

bindata/manifests/plugins/sriov-cni.yaml, pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go
When used with upstream installation, multus fails because it's not able to find the sriov cni binary under /opt/cni/bin (see https://github.com/openshift/sriov-network-operator/issues/34)
This PR maintains the current behaviour while making it possible to override the binary path through an env variable.
=> Make it possible to override the cni binary path

doc/quickstart.md
I got somehow confused on how to test locally changes to the network config daemon.
This pr adds a bit of doc in that regard.
=> Add doc to test config daemon changes locally

bindata/scripts/enable-kargs.sh, pkg/plugins/generic/generic_plugin.go
The generic plugin uses grubby to check if `intel_iommu=on` and `iommu=pt` are set as kernel parameters.
This assumes that grubby is installed and that the current host is rhel based, which might not be the case in upstream. 
This pr checks for grubby existance and if it's not installed simply raises an error without having the node config daemon restart
=> Don't crash if grubby is not installed

doc/quickstart.md
I think the doc for installing the operator has a copy paste error.
=> Fix operator installation instructions

Makefile, deploy/operator.yaml, doc/quickstart.md, hack/deploy-setup.sh, hack/run-e2e-test.sh
This is a follow up to https://github.com/openshift/sriov-network-operator/pull/47 
With that, if I want to deploy the operator upstream I need to provide my own (modified) operator deployment manifest or have some script machinery to hack the one from the operator repository, which results in a non pleasant user experience.
With this pr I add a `deploy-setup-k8s` rule that sets the env variable to the value expected upstream.
Normally the default value will be used and the current path will be preserved.
=> Add a deploy-setup-k8s rule to deploy on upstream

doc/quickstart.md
`make deploy-setup` defaults the command to use to `oc`. 
This pr documents how to override the command to use `kubectl` in case of upstream.
=> Add info about using kubectl instead of oc in case of k8s

pkg/controller/sriovnetwork/sriovnetwork_controller.go
SRIOV operator watches net-attach-def events and
filters net-attach-def of sriov type based on
Owner Reference. Owner Reference may be nil if not
created by SR-IOV Operator.
=> BUG 1754738: fix nil reference

test/e2e/e2e_test.go
sriov device plugin requires resource name to not
contain `-` character.
=> e2e: fix invalid resource name

manifests/art.yaml
This gives us different CSVs for different releases (e.g. 4.2 and 4.3)
when we're building OCP downstream.
This should be cherry-picked back to 4.2 but the problem we have (duplicate CSVs) will go away for now even if just 4.3 gets changed.
=> add manifests/art.yaml

README.md, doc/quickstart.md, manifests/4.3/sriov-network-operator.v0.0.1.clusterserviceversion.yaml
change sriov-capable label to network-sriov.capable
which is consistent with nfd sriov label.
=> use consistent sriov label

pkg/controller/sriovnetwork/sriovnetwork_controller.go
SRIOV operator watches net-attach-def events and
filters net-attach-def of sriov types based on
Owner Reference. Owner Reference may be nil if not
created by SR-IOV Operator.
Backport #80
=> Bug 1755188: fix nil reference

bindata/manifests/cni-config/sriov-cni-config.yaml
VlanQoS is an int value in SR-IOV CNI, the generated
config should be integer instead of string.
=> remove quotes of vlanQoS in generated net-attach-def

Dockerfile.sriov-network-config-daemon, Dockerfile.sriov-network-config-daemon.rhel7
mstflint is only required for the mellanox plugin, which is a no-op on IBM Z.
=> Do not require mstflint on s390x

Dockerfile.sriov-network-config-daemon, Dockerfile.sriov-network-config-daemon.rhel7
mstflint is only required for the mellanox plugin, which is a no-op on IBM Z.
This is a backport of commit acdee096d503f5aa772b31c1e880b2e0cf00e94d.
=> Bug 1772696: 4.2: Do not require mstflint on s390x

pkg/apis/sriovnetwork/v1/helper.go, pkg/controller/sriovnetwork/sriovnetwork_controller.go, test/e2e/e2e_test.go
According to https://github.com/kubernetes-sigs/controller-runtime/pull/675, cross namespace owner reference is disallowed by Kubernetes. In this PR, we use the finalizer for the garbage collection.
=> Bug 1770668: Optimize SrivoNetwork CR update logic

cmd/sriov-network-config-daemon/start.go, deploy/crds/sriovnetwork.openshift.io_sriovnetworknodestates_crd.yaml, manifests/4.4/sriov-network-operator-sriovnetworknodestate.crd.yaml, pkg/daemon/daemon.go, pkg/utils/driver.go, pkg/utils/utils.go
Check whether desired state is the same as the current one before
executing.
=> BUG 1798043: Optimize VF configure logic

cmd/manager/main.go, deploy/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies_crd.yaml, manifests/4.5/sriov-network-operator-sriovnetwork.crd.yaml, manifests/4.5/sriov-network-operator-sriovnetworknodepolicy.crd.yaml, manifests/4.5/sriov-network-operator-sriovnetworknodestate.crd.yaml, manifests/4.5/sriov-network-operator-sriovoperatorconfig.crd.yaml, pkg/apis/sriovnetwork/v1/sriovnetworknodepolicy_types.go
Also, sync the 4.5 CRD in the manifest directory, as it was not done in the operator-sdk upgrade PR.
=> Bug 1814919: Prevent user from setting numVfs to '0'

pkg/apply/apply.go, pkg/apply/merge.go
`DeepEqual` compares all the fields in the objects, however, we want to only focus on the fields set by the controller. This PR will also fix the problem that the controller keeps reconciling, due to the `DeepEqual` always returns false.
=> Use DeepDerivative to compare the the kube object content

test/conformance/tests/sriov_operator.go, test/conformance/tests/vfs_assignement.go
This will allow us to filter sriov tests when using the tests as a dependency
=> Add the [sriov] tag to conformance tests, to make it easier to filter

test/conformance/tests/sriov_operator.go, test/conformance/tests/vfs_assignement.go, test/util/namespaces/namespaces.go
As these tests are going to be part of cnf tests, we don't want to disrupt pre-existing network configurations.
Here we prefix the network names / network configurations with test- and delete only those.
=> Bug 1833436: Focus the cleanup only on sriov networks / policies created by the tests

pkg/daemon/daemon.go
This commit fix the draining watch.
Before this commit we stop the informer and use is lister to update the node.
That didn't update the node in the cluster only the object itself so the node object
inside the cluster stuck on Draining for ever.
=> Bug 1834141: Fix draining watch

test/conformance/tests/sriov_operator.go, test/conformance/tests/vfs_assignement.go, test/util/images/images.go, test/util/network/network.go, test/util/pod/pod.go
This Commit is base on the CNF repo change https://github.com/openshift-kni/cnf-features-deploy/pull/196
=> Bug 1834371: Change the tests image

test/conformance/tests/sriov_operator.go, test/util/cluster/cluster.go
This commit waits for the config-daemon pod to be running before fetching the logs
This fix the following error
```
Message: "container \"sriov-network-config-daemon\" in pod \"sriov-network-config-daemon-d55s9\" is waiting to start: ContainerCreating",
```
=> Bug 1840160: Wait for the pod to be running before fetching the logs

pkg/daemon/daemon.go
When the get nodes in uncordon fails, the daemon exits and the node remains uncordoned.
When the get of the device plugin pod fails, the daemon does not restart it and the change requested does not get applied.
=> Bug 1840104: Make the daemon more resilient to failures.

cmd/sriov-network-config-daemon/start.go, pkg/daemon/writer.go, pkg/utils/utils.go
Force close connections on heartbeat failure, when heartbeat failed, we invoke closeAllConns and reestablish new connections. We use the writer's periodic Get() call as hearbeat singal, to detect whether the HTTP connection to the apiserver is still healthy.
=> Bug 1836212: Introduce a custom Dailer to close TCP connections when heartbeat fails

cmd/sriov-network-config-daemon/start.go, pkg/daemon/writer.go, pkg/utils/utils.go
Force close connections on heartbeat failure, when heartbeat failed, we invoke closeAllConns and reestablish new connections. We use the writer's periodic Get() call as hearbeat singal, to detect whether the HTTP connection to the apiserver is still healthy.
This is a manual cherry pick of https://github.com/openshift/sriov-network-operator/pull/200
=> Bug 1841063: [Release-4.4] Introduce a custom Dailer to close TCP connections when heartbeat fails

pkg/utils/utils.go
rdma_cm uses node_guid of VF for RoCE, but when VFs are created the node_guid is zero, assigning the administrator mac then unbind/bind the VF's driver can set the node_guid
=> Unbind/Bind VFs after assigning admin mac to set node_guid

deploy/crds/sriovnetwork.openshift.io_sriovnetworknodestates_crd.yaml, manifests/4.6/sriov-network-operator-sriovnetworknodestate.crd.yaml, pkg/apis/sriovnetwork/v1/sriovnetworknodestate_types.go
OLM doesn't allow CRD to introduce new required fields during an upgrade.
=> Bug 1839754: Remove required feilds from SriovNetworkNodeState CRD

pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go
node affinity still exists when all policies are deleted.
try removing daemon affinity when deleting plugin pods.
=> cleanup DaemonSet affinity when deleting plugin pods

test/conformance/tests/sriov_operator.go, test/util/cluster/cluster.go, test/util/nodes/nodes.go
By setting the optional NODES_SELECTOR env variable, we limit the nodes impacted by the tests to those matching that label selector.
=> Add an optional label selector to limit the nodes impacted by the tests.

test/conformance/test_suite_test.go, test/conformance/tests/init.go, test/e2e/e2e_tests_suite_test.go, test/util/clean/clean.go, test/util/client/clients.go, test/util/namespaces/namespaces.go
This is useful when using the suite as a dependency, to restore the cluster to the original state.
=> Export a clean.All function that removes all the leftovers from the conformance suite

pkg/webhook/validate.go, pkg/webhook/validate_test.go
Previously partition overlap was rejected only when
policy.Spec.NicSelector.RootDevices is configured.
=> Detect partition overlap regardless of rootDevices

test/conformance/tests/sriov_operator.go, test/util/cluster/cluster.go, test/util/discovery/discovery.go
This patch adds a check for discovery mode and a resource check for tests with a shared policy.
Other tests will be covered in a follow up patch.
=> Add discovery mode for sriov tests with shared policy

test/util/cluster/cluster.go
cluster.FindOneSriovDevice was modified for discover mode to
return a device with biggest count of available vfs.
This check was since added to discovery.DiscoveredResources,
and is hence not needed here.
This change reverts the function to it's previous version
=> Revert changes to FindOneSriovDevice

cmd/sriov-network-config-daemon/start.go, pkg/daemon/writer.go, pkg/utils/utils.go
1. When reseting PF MTU, the daemon reset it to actual initial value.
2. When setting MTU, the daemon always set the MTU of VF to the desired value.
3. Set the VF MTU to PF's if MTU is not provided by users.
=> BUG 1854775: Improve the MTU set/reset logic

doc/quickstart.md
- Add a clause to the Prerequisites section in the quick-start guide
about the supported models of SRIOV hardware.
- Add a note about the possibility of using unsupported models as well, by
disabling the webhook for validating the NIC's model.
This could prevent frustration among users and developers
who do not understand why the SRIOV functionality is not working well,
and keep them aware that if their SRIOV NIC is not supported,
at least for development testing, they might be able to work around this.
Signed-off-by: alonSadan <asadan@redhat.com>
=> Add prerequisite about supported NIC model

test/conformance/tests/sriov_operator.go
Two tests fix:
- Waiting for NAD creation (if Get fails because of not found, wait again)
- Use the global `test-*` network name so the network is sweeped by the cleaning
=> Fix flaky tests

manifests/4.5/sriov-network-operator.v4.5.0.clusterserviceversion.yaml
The issue of ENABLE_ADMISSION_CONTROLLER doesn't take effect
was fixed in 4.6/master branch. When that PR(https://github.com/openshift/sriov-network-operator/pull/211)
was proposed, 4.6 manifests were not created yet, so the change
went into 4.5 manifests(on 4.6 branch). This may cause confusion
that ENABLE_ADMISSION_CONTROLLER flag is supported in 4.5 release
which isn't true. This commit remove the env var change in 4.5
manifests(on 4.6 branch) to avoid confusion.
=> Remove ENABLE_ADMISSION_CONTROLLER in 4.5 manifests

doc/quickstart.md
I was asked in https://github.com/openshift/sriov-network-operator/pull/287#discussion_r452157087.
to add explanation about the need to disable the webhook in order to
use sriov-operator on a a non supported SRIOV NIC.
In this PR I added the steps for disabling the webhook.
further details can be found in the previous PR:
https://github.com/openshift/sriov-network-operator/pull/287
Signed-off-by: alonSadan <asadan@redhat.com>
=> Add note about disabling webhook for unsupported NICs

test/conformance/tests/sriov_operator.go
This will fix the issue that the test kill the node by setting down the interface connected to the ovs external bridge
```
6: ens1f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master ovs-system hwmode VEPA
```
=> Bug 1870669: Fix the isInterfaceSlave function

pkg/utils/utils.go
VF mtu may be discovered as zero if it's attached to a Pod
or not in the host namespace for various reasons.
=> Bug 1870547: Not update VF mtu if it's not retrievable or zero

pkg/daemon/daemon.go
When the fetch of the state fails, a sync error is written on the status.
Then, on next reconciliation loops, if the local generation equals to the remote one, that error is never reset. 
Here we assume that if the two versions are identical, the sync happened successfully and we reset the message.
=> Bug 1875330: Reset sync error if local status generation is equal remote.

Makefile, bindata/scripts/enable-rdma.sh
This patch add support for enabling RDMA and installing the needed packages on the Ubuntu OS and updating the Makefile rules for support deploying the operator on Ubuntu
=> Support SR-IOV Network operator for Ubuntu

test/conformance/tests/sriov_operator.go, test/util/cluster/cluster.go
Fix the macvlan test
This commit add a new list in the test for the VF drivers.
The issue with this test was that the VF drivers are not the same as the PF drivers for intel for example (mlx is the same)
This PR is base on https://github.com/openshift/sriov-network-operator/pull/345
=> Bug 1880990: Fix macvlan test

test/conformance/tests/sriov_operator.go
This commit change the search for the interface.
different base image versions like centos and ubi8 have a different outputs for the bridge link command.
This change will use the contains function and not search for the exact split string
=> Bug 1880990: Fix the pf down test

test/conformance/test_suite_test.go, test/conformance/tests/sriov_operator.go
This commit changes the interface we use for the MTU test.
Is better not to use the main SDN interface for the MTU test,
because the test change the MTU of the PF to 9000 and packets start
dropping in the other nodes that have MTU set to 1500.
This commit also add the clean method to the beforeSuite function
=> Bug 1880990: Fix the MTU test

hack/env.sh
Signed-off-by: Pedro Ibáñez <pedro@redhat.com>
If skopeo is not installed on the system the build succeed but the image name is incorrect and can't be pulled, this PR verifies if skopeo is installed, otherwise will exit with rc 1
Fixes #342
=> Bug 1878677: Adding a check to verify if skopeo is installed, otherwise exit 1

test/conformance/tests/sriov_operator.go, test/util/network/network.go
- Tests starting when devices are not available yet. Waiting for them to
appear under the node.
- A macvlan flake complaining about device not ready, sticking with default.
=> Bug 1880990: SR-IOV conformance flakes.

test/conformance/tests/sriov_operator.go
While removing from discovery mode, a syntax error was introduced.
=> Bug 1880990: Fix syntax error in conformance test.

test/conformance/tests/sriov_operator.go
The test assumes a fixed number of available vfs, skipping for now.
=> Bug 1880990: Skip vf allocation in case of discovery mode.

test/conformance/tests/sriov_operator.go
Without doing so, it causes a panic.
=> Bug 1880990: Move the skip inside an It context

must-gather/Dockerfile.rhel7
Updating sriov-network-must-gather builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/990044f295fb1d5e238823902962dbcfa1c041c9/images/sriov-network-must-gather.yml
=> Bug 1878163: Updating sriov-network-must-gather builder & base images to be consistent with ART

Dockerfile.rhel7
Updating sriov-network-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/990044f295fb1d5e238823902962dbcfa1c041c9/images/sriov-network-operator.yml
=> Bug 1878163: Updating sriov-network-operator builder & base images to be consistent with ART

test/conformance/tests/sriov_operator.go
In regular mode, this is ensured by the fact that we configure the devices only on the first node,
and as a side effect both pods get scheduled on the same node. This is not true in discovery mode
and with this change we ensure that.
=> Bug 1884251: Conformance test: make sure that the hostnetwork pod and the test pod run on the same node.

bindata/manifests/operator-webhook/003-webhook.yaml, pkg/webhook/validate.go, pkg/webhook/validate_test.go, pkg/webhook/webhook.go
There are default sriovnetworknodepolicy and sriovoperatorconfig CRs
which we don't want user to delete although they can be re-created.
This PR adds support for DELETE operation in operator-webhook to
block the deletion of default node policy and operator config CRs.
=> Add webhook delete operation

Dockerfile.sriov-network-config-daemon.rhel7
Updating sriov-network-config-daemon builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/sriov-network-config-daemon.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating sriov-network-config-daemon builder & base images to be consistent with ART

Dockerfile.rhel7
Updating sriov-network-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/sriov-network-operator.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating sriov-network-operator builder & base images to be consistent with ART

Dockerfile.webhook.rhel7
Updating sriov-network-webhook builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/sriov-network-webhook.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating sriov-network-webhook builder & base images to be consistent with ART

must-gather/Dockerfile.rhel7
Updating sriov-network-must-gather builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/sriov-network-must-gather.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating sriov-network-must-gather builder & base images to be consistent with ART

must-gather/Dockerfile.rhel7
PR #343 reverts the must-gather base image from cli to base.
This is to change it back.
=> Bug 1879379: Use cli base image for must-gather image building

test/conformance/tests/sriov_operator.go
There are a couple of tests where we don't wait for the resource number to be ready.
This makes the tests flakes as the pod waiting time must take also into account the time
needed for having the resources to be ready.
=> Bug 1890088: Conformance tests: Wait for the resources to be ready.

Makefile
=> Not using -mod=vendor for kustomize and controller-gen target

Makefile, bindata/scripts/enable-rdma.sh
Support SR-IOV Network operator for Ubuntu
This patch add support for enabling RDMA and installing the needed
packages on the Ubuntu OS and updating the Makefile rules for support
deploying the operator on Ubuntu
Fixes #380
=> sync dev branch 2020-10-30

Makefile, config/crd/bases/sriovnetwork.openshift.io_sriovibnetworks.yaml, config/crd/bases/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml, config/crd/bases/sriovnetwork.openshift.io_sriovnetworknodestates.yaml, config/crd/bases/sriovnetwork.openshift.io_sriovnetworks.yaml, config/crd/bases/sriovnetwork.openshift.io_sriovoperatorconfigs.yaml, manifests/4.7/sriov-network-operator-sriovibnetworks_crd.yaml, manifests/4.7/sriov-network-operator-sriovnetwork.crd.yaml, manifests/4.7/sriov-network-operator-sriovnetworknodepolicy.crd.yaml, manifests/4.7/sriov-network-operator-sriovnetworknodestate.crd.yaml, manifests/4.7/sriov-network-operator-sriovoperatorconfig.crd.yaml
In operator-sdk 1.0.1, the defaule generated CRD version is v1beta1.
We change it back to v1, as we've been using v1 for a long time.
=> Bump CRD version to v1

doc/quickstart.md
Makefile rule `operator-sdk` has been removed
Closes issue #381
=> Reflect updated Makefile in Quickstart doc

api/v1/sriovoperatorconfig_types.go, config/crd/bases/sriovnetwork.openshift.io_sriovoperatorconfigs.yaml, pkg/daemon/daemon.go
SR-IOV Operator drains nodes before applying any configuration on the node NIC. this usually takes some time since it needs to evict the pods on that node. 
This PR adds a new DisableDrain flag in Operator Config CRD to allow disabling of drain process when applying a new policy which in turn saves the waiting time.
=> Add DisableDrain flag into operator config for efficient debugging

hack/env.sh
In order to allow running without skopeo install,
add support to set SKIP_VAR_SET,
which will skip env settings, skopeo dependency,
and just validate all env vars are set.
Fixes: https://github.com/openshift/sriov-network-operator/issues/395
Signed-off-by: Or Shoval <oshoval@redhat.com>
=> Add an option to skip variable setting in hack/env.sh

README.md, api/v1/helper.go, api/v1/helper_test.go, api/v1/sriovnetwork_types.go, api/v1/testdata/TestRendering/chained.golden, api/v1/testdata/TestRendering/simple.golden, bindata/manifests/cni-config/sriov-cni-config.yaml, config/crd/bases/sriovnetwork.openshift.io_sriovnetworks.yaml, manifests/4.7/sriov-network-operator-sriovnetwork.crd.yaml, test/conformance/tests/sriov_operator.go, test/util/network/network.go
In order to generate a network attachment definition that chains the SR-IOV CNI configuration with additional metaplugins (such as VRF, or firewall), we expose a new MetaPluginsConfig where to put the json list of the extra configurations, in the form of
```
{
// meta plugin A config
},
{
// meta plugin B config
}
```
=> Add an optional SriovNetwork section: additional metaplugins

bindata/manifests/operator-webhook/003-webhook.yaml, pkg/webhook/webhook.go
Currently operator-webhook denies every delete operation with:
denied the request: unexpected end of JSON input
=> Use the right object when webhook delete operation

controllers/sriovoperatorconfig_controller.go, main.go
Currently webhook and injector are deployed by default ignoring the environment variable ENABLE_ADMISSION_CONTROLLER which cause the operator to broke on vanilla kubernetes
This commit restrict deploying  webhook and injector when ENABLE_ADMISSION_CONTROLLER is true
Fixes #401
=> Deploy AdmissionController when ENABLE_ADMISSION_CONTROLLER is true

controllers/sriovnetworknodepolicy_controller.go, controllers/sriovnetworknodepolicy_controller_test.go, go.mod
The current implementation only assigns the first label found in the policy selector.
This causes two issues: do not use the second label specified by the user, and given the fact that the iteration on a map is executed in a random way, the definition of the daemonset is different every reconciliation loop, causing a restart of the pods under the daemonsets.
=> Bug 1898580: fix the sriov daemon selector assignement.

pkg/daemon/daemon.go
Work around a udev race condition where NM_UNMANAGED=1 
added to a device path after multiple repeated move operations
of a VF from the host namespace to a pod and back.
=> Work around udev race condition related to NM_UNMANAGED=1

Makefile, README.md, cmd/sriov-network-config-daemon/start.go, pkg/daemon/daemon.go, pkg/daemon/plugin.go, pkg/daemon/writer.go, pkg/plugins/virtual/virtual_plugin.go, pkg/utils/utils.go, pkg/utils/utils_virtual.go
This PR adds support for running (initially) in an OpenShift on OpenStack environment.  In a VM environment, only VFs are attached (no PF) and the VFs represent an underlying OpenStack network.  This PR removes the necessity of accessing a PF and uses additional information passed into the VM by the OpenStack metadata service to include underlying network mappings in the sriovnetworknodestate.  In addition, the exposed underlying network information can be used to select networks for a policy.  
This PR is in conjunction with a PR in  k8snetworkplumbingwg/sriov-network-device-plugin repository.  
This PR is to allow a review of the concept.
=> Add support for running in a virtual machine -- Remove PF dependency

test/conformance/tests/sriov_operator.go, test/util/cluster/cluster.go
When running the tests against a single cluster, configuration changes may trigger reboots. Here we ignore the error, assuming that the cluster will be back within the timeout. Other calls to the api server are done before reaching this stage, so it's safe to assume that running the tests against a wrong cluster will result in an earlier error.
=> Tests: ignore get errors when checking for sriov stable

controllers/sriovoperatorconfig_controller.go
The reconciliation loop of the policy sets the selector to worker/linux if the one in the config is empty. 
The config reconciliation, on the other hand, sets it to empty. When this happens, a new reconciliation is triggered and the pdos are recreated.
This causes a restart of the dp / cni pods every 5 minutes
=> Bug 1901909: do not set the node selector in the dp / cni daemons if empty in config.

hack/env.sh
If `SKIP_VAR_SET` is set, it should check the SRIOV_* env vars
because those are the ones that the user should override,
and not the DIGEST* ones, which are just intermediate values.
Signed-off-by: Or Shoval <oshoval@redhat.com>
=> Fix logic in case SKIP_VAR_SET is set

test/util/clean/clean.go, test/util/namespaces/namespaces.go
This allows clients to call sriov stable even in the single node scenario.
By having the policy cleanup the last operation of Clean, we ensure we are able to perform the other cleanings before the node is rebooted, avoiding unwanted errors.
=> Make the clean policies the last operation of clean.Clean.

Makefile
Automatically copies generated `yaml` files from `./config/crd/bases` to `./manifests/4.7`
**Note:**  the  `./manifests/4.7` dirictory conatins 3 additional files, I've not found thier sources, so they probably should be continue to be manually updated.
The files are:
- sriov-network-operator.v4.7.0.clusterserviceversion.yaml
- sriov-network-operator-sriovnetwork.crd.yaml
- image-references 
Signed-off-by: Alexey Roytman <roytman@il.ibm.com>
=> Automatically copy generated yaml files to the ./manifests/4.7 dir

api/v1/helper.go, deploy/role.yaml, deploy/role_binding.yaml, pkg/daemon/daemon.go, pkg/webhook/validate.go
This patch implements a new field to the SriovOperatorConfig CRD
with name "unsupportedNicIdMap". This setting allows the configuration
of unsupported NIC models, example: [{"X520":"8086 154d 10ed"}
=> Allow non supported hardware for testing purposes

go.mod, pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go, pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller_test.go
This is a manual cherry pick of https://github.com/openshift/sriov-network-operator/pull/411
The current implementation only assigns the first label found in the policy selector.
This causes two issues: do not use the second label specified by the user, and given the fact that the iteration on a map is executed in a random way, the definition of the daemonset is different every reconciliation loop, causing a restart of the pods under the daemonsets.
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
=> Bug 1898595: Fix the sriov daemon selector assignement

api/v1/helper.go, api/v1/sriovnetworknodepolicy_types.go, api/v1/sriovnetworknodestate_types.go, cmd/sriov-network-config-daemon/start.go, controllers/sriovnetworknodepolicy_controller.go, pkg/daemon/daemon.go, pkg/daemon/writer.go, pkg/utils/utils_virtual.go
[Addresses Issue](https://github.com/openshift/sriov-network-operator/issues/399)
When OpenShift is deployed on OpenStack, OpenStack provides additional metadata about networks that can be used by the sriov-network-operator. This metadata specifies which OpenStack networks (UUID) are connected to which interface of the VM. In addition, if Device Role Tagging is used, the metadata can also provide labels that allow the grouping of VF resources.
=> Add support for OpenStack metadata

bindata/manifests/webhook/server.yaml
--insecure was added in network-resources-injector to allow use
of third-party CA when it's set to false (default). This is not
needed in openshift which uses CA operator for injecting cabundle.
=> add --insecure=true flag for network-resouces-injector daemon

go.mod, pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go, pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller_test.go
The current implementation only assigns the first label found in the policy selector.
This causes two issues: do not use the second label specified by the user, and given the fact that the iteration on a map is executed in a random way, the definition of the daemonset is different every reconciliation loop, causing a restart of the pods under the daemonsets.
This is a manual cherry pick of https://github.com/openshift/sriov-network-operator/pull/413
=> Bug 1898594: Fix the sriov daemon selector assignement

test/conformance/tests/sriov_operator.go
This commit fix a panic when the test is not able to find a main PF in discovery mode
```
•! Panic [15.745 seconds]
[sriov] operator
/remote-source/app/vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:64
Custom SriovNetworkNodePolicy
/remote-source/app/vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:827
Configuration
/remote-source/app/vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:835
Main PF
/remote-source/app/vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:1044
should work when vfs are used by pods [It]
/remote-source/app/vendor/github.com/k8snetworkplumbingwg/sriov-netw …
```
=> Bug 1914852: Fix Main PF panic

must-gather/Dockerfile.rhel7
This should fix the problem of oc adm must-gather not finding oc binary
=> Bug 1879379: Change must-gather/Dockerfile.rhel7 to use must-gather image

controllers/sriovnetworknodepolicy_controller.go
LinkType is not detectable for eth vfio-pci device using
netlink library which results in failure when exposing
vfio-pci resources.
=> [release-4.7] Bug 1930469: Only add linkType selector for infiniband devices

test/conformance/tests/sriov_operator.go, test/util/cluster/cluster.go
Single node environments can take much longer to stabilize than environment with multiple nodes. This can cause existing tests to fail due to the timeouts not being long enough. This PR increases the timeouts if a single node environment is detected.
=> Increase tests timeout for single node test environments

manifests/4.8/sriov-network-operator.v4.8.0.clusterserviceversion.yaml
Add metadata to indicate availability of sriov-network-operator on the ppc64le architecture.
=> Bug 1949202: Add metadata for ppc64le

bindata/manifests/daemon/daemonset.yaml, bindata/manifests/operator-webhook/server.yaml, bindata/manifests/plugins/sriov-cni.yaml, bindata/manifests/plugins/sriov-device-plugin.yaml, bindata/manifests/webhook/server.yaml, manifests/4.8/sriov-network-operator.v4.8.0.clusterserviceversion.yaml
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
=> Add management workload annotations

bindata/manifests/daemon/daemonset.yaml, bindata/manifests/operator-webhook/server.yaml, bindata/manifests/plugins/sriov-cni.yaml, bindata/manifests/plugins/sriov-device-plugin.yaml, bindata/manifests/webhook/server.yaml, manifests/4.8/sriov-network-operator.v4.8.0.clusterserviceversion.yaml
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
=> Rename workload annotations

test/util/clean/clean.go
https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/121
=> Bug 1955120: Move RestoreNodeDrainState up in clean.All()

bindata/manifests/webhook/003-webhook.yaml
This commit fix the network injector webhook to stuck the all cluster.
https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/116 move the admission version to v1
In v1 the default `FailurePolicy` is `Fail` and not `Ignore` as v1Beta1
=> Bug 1958643: Fix network injector webhook

Makefile, cmd/sriov-network-config-daemon/start.go, deploy/clusterrole.yaml, manifests/4.7/sriov-network-operator.v4.7.0.clusterserviceversion.yaml, pkg/daemon/daemon.go, pkg/plugins/generic/generic_plugin.go
The config daemon instance on each node need to compete for the 'Draining' lock before
it can draining/rebooting a node.
After a config daemon instance gets the lock, it checks its MachineConfigPool conditions.
If the MCP is in ready state, it will pause the MCP then process, otherwise, it wait for
the MCP getting ready. The MCP will be resumed after the config daemon and release the
lock after the config dameon finishes its work.
=> [release-4.7] Bug 1960103: Pause MCP before draining/rebooting node

bundleci.Dockerfile
The current one copies bundle/manifests which is not what we use for CI.
Here we add a new one to serve CI purpouses.
=> Bug 1966620: Add an openshift specific bundle to use for CI

manifests/4.8/sriov-network-operator.v4.8.0.clusterserviceversion.yaml
PR #495 added annotations
required for supporting the workload partitioning feature for ocp 4.8.
However, OLM has a bug in processing the annotations (BZ 1950047).
This PR provides a workaround necessary to release the workload
partitioning in OCP 4.8.
=> Bug 1966561: add OLM bug workaround for workload partitioning

bundleci.Dockerfile
ci-operator does not support ImageStream resources
=> Exclude non yamls from bundleci.Dockerfile

main.go
Using 2 managers for the same controllers causes inconsistency in
objects reconcilation. For example we saw a problem with some SriovNetwork
update events not reaching the controller (Reconcile was not triggered).
Using the same Mgr as the specified client for the controller solves these kind of problems.
Cherry-pick from https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/175
Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>
=> Bug 1993007: Use GlobalMgr for SriovNetwork controllers

manifests/art.yaml
Currently, the skipRange substitution for product builds is a noop.
This change should fix that.
=> Bug 1994997: Fix olm.skipRange substitution

pkg/webhook/mutate.go
LinkType is not a mandatory selector, sometimes it
may have issue detecting attached devices or devices
with empty linkType value returned from netlink interface
=> Bug 2027893: unset default linkType value in operator webhook

pkg/webhook/mutate.go
LinkType is not a mandatory selector, sometimes it
may have issue detecting attached devices or devices
with empty linkType value returned from netlink interface
=> Bug 2027911: unset default linkType value in operator webhook

api/v1/helper.go, api/v1/sriovnetworknodestate_types.go, bundle/manifests/sriovnetwork.openshift.io_sriovnetworknodestates.yaml, config/crd/bases/sriovnetwork.openshift.io_sriovnetworknodestates.yaml, manifests/4.9/sriovnetwork.openshift.io_sriovnetworknodestates.yaml, pkg/utils/utils.go
To set the GUID to VF, we need to set the admin MAC and reload the
VF driver. It will take a long time if users set big 'numVFs'. This
PR changes the logic to only reload the VF driver when isRdma is
set. So that, users not using ROCE will no longer need to wait for
the VF driver reload.
=> Bug 2040122: [Release 4.9] Reload VF driver only when rdma is enabled

bindata/manifests/switchdev-config/files/switchdev-configuration-after-nm.sh.yaml, bindata/manifests/switchdev-config/files/switchdev-configuration-before-nm.sh.yaml, bindata/manifests/switchdev-config/switchdev-units/NetworkManager.service.yaml, bindata/manifests/switchdev-config/switchdev-units/switchdev-configuration-after-nm.yaml, bindata/manifests/switchdev-config/switchdev-units/switchdev-configuration-before-nm.yaml
It is found that VF netdev disappears after it was successfully
created (observed via ip link show). While investigating the root
cause, setting addtional dependency in NetworkManager.service
as temporary fix to the issue.
This commits also changes service and script names to lower case
(cherry picked from commit 6325355230a16d06426810b8ab1c76cd17a42787)
=> Bug 2041734: ensure switchdev service dependencies

pkg/webhook/validate.go, pkg/webhook/validate_test.go
Backport of
https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/210.
In `staticValidateSriovNetworkNodePolicy`, we now allow a NicSelector to
only have NetFilter defined.
This will be useful for the OpenStack platform, where we can request a
Network Node Policy only by its Network ID.
=> Bug 2029867: backport for allowing netFilter to be set alone in NicSelector

pkg/daemon/daemon.go
Fix the issue that generic plugin Apply won't be invoked if no supported
vendor NICs in the host.
(cherry picked from commit 1d954a5304283f62808abbe13c55c6dd7b2b4083)
=> Bug 2033129: Run generic plugin Apply when no vender plugin loaded

api/v1/helper.go, cmd/sriov-network-config-daemon/start.go, pkg/utils/utils_virtual.go, pkg/webhook/validate.go, pkg/webhook/validate_test.go
This is a manual backport (was in cherry-pick conflict otherwise).
This commit fix the validation webhook to support virtual workers using
PCI passthrough
=> Bug 2049774: Fix webhook for virtual workers

Makefile
Don't overwrite the supported NICs downstream. We maintain a different
list of NICs than upstream does.
=> Bug 2072498: fix make bundle

pkg/daemon/daemon.go
This commit allow to still pause the MCP when running on OCP.
This is needed when you have only 1 node in the cluster and the drainSkip is true
=> Bug 2066401: Support pause MCP on SNO

config/manager/manager.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml
Remove must-gather image reference `SRIOV_OPERATOR_MUST_GATHER_IMAGE` as it is deprecated since `4.11`
https://github.com/openshift/must-gather/pull/297
Signed-off-by: Andrea Panattoni <apanatto@redhat.com>
=> Remove references to must-gather image

pkg/daemon/daemon.go
=> Bug 2095210: [release 4.8] Don't check MCP state when node in Draining_MCP_Paused state

pkg/daemon/daemon.go
This commit is needed when using DPDK with vhost-net in virtio mode.
We must load the vhost-net kernel module if we don't want the dpdk
application to run with privilege
=> Bug OCPBUGS-796: load vhost-net kernel module

deploy/configmap.yaml, deployment/sriov-network-operator/templates/configmap.yaml, doc/supported-hardware.md
ConnectX-6 Lx support is currently available upstream.
Signed-off-by: William Zhao <wizhao@redhat.com>
=> NHE-203: Add Nvidia MLX5 ConnectX-6 Lx Support

bundle/manifests/supported-nic-ids_v1_configmap.yaml, config/manifests/bases/sriov-network-operator_configmap.yaml
We had this NIC supported in previous releases, and it was missed in 4.12 probably due to a bad copy/paste.
We need this NIC to be supported, for the virtualized environments (e.g. OpenStack).
=> OCPBUGS-1235: Add missing Red Hat Virtio network device into supported nics

deploy/configmap.yaml, deployment/sriov-network-operator/templates/configmap.yaml, doc/supported-hardware.md, doc/vendor-support.md, pkg/plugins/generic/generic_plugin.go, pkg/plugins/generic/generic_plugin_test.go, pkg/plugins/mellanox/mellanox_plugin.go, pkg/utils/switchdev.go, pkg/utils/utils.go, pkg/utils/utils_mlx.go
Gather commits using
```
$ git --no-pager log --cherry-pick --format="%h %s" --left-only --no-merges upstream/master...openshift/master
42eb7e94 Fix the issue introduced in https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/240/files#r808624002
34b3fc31 move mellanox mstconfig functions to the utils_mlx.go
3a2ee559 update yaml configuration to allow for control plane status detection
64a59431 add automation path for components to operate in a hypershift environment (without mco)
9ca96bc9 add openshift context struct for openshift specific metadata
6cdb4827 improve drain check
61a08207 Adding suport for Octeon DPU family
c3fd5f64 update openshift-api to include external control plane topology enum
711302e0 support external control plane
c5c69732 lint: fix goconst issues …
```
=> Sync k8snetworkplumbingwg/master 2022_09_22

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/rbac/sriov-network-config-daemon_clusterrole.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
The network-config-daemon needs access to the resource "infrastructures" in the API group "config.openshift.io".
This resource is needed for allowing control plane status detection. This was updated upstream in commit:
"update yaml configuration to allow for control plane status detection" a13b59e7f8f74d
Also ran "make bundle" to update the manifest files.
=> OCPBUGS-2126: Update RBAC files for the network-config-daemon

config/manager/manager.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
This backport is about cleaning the unused `SRIOV_OPERATOR_MUST_GATHER_IMAGE` environment variables from deployment files.
=> [release-4.11] OCPBUGS-694: Remove must gather

deploy/configmap.yaml, deployment/sriov-network-operator/templates/configmap.yaml, doc/supported-hardware.md, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
```
$ git --no-pager log --cherry-pick --format="%h %s" --left-only --no-merges upstream/master...openshift/master                                                                                                                   
1c0bf417 daemon: fix NM udev path
c7c06b1a Add SIGTERM flag to avoid flaky updates
431e210f Add terminationGracefulPeriodSeconds to config daemonset
38755ee8 Remove unused dependencies
454c4d28 Add graceful node shutdown support to config daemon
3a2ee559 update yaml configuration to allow for control plane status detection
6cdb4827 improve drain check
20fce6cb Add NVIDIA ConnectX-7 to supported NICs
61a08207 Adding suport for Octeon DPU family
$ git cherry-pick 20fce6cb 454c4d28 38755ee8 431e210f c7c06b1a 1c0bf417
```
/cc @pacevedom
=> OCPBUGS-2109: Sync 2022 10

pkg/plugins/generic/generic_plugin.go, pkg/plugins/generic/generic_plugin_test.go, pkg/utils/switchdev.go, pkg/utils/utils.go
We need to check in the drain function also if VFs exist If they exist we need to check if any other configuration is required (link driver and MTU)
If a change to the VF is requested we should drain the node because we can have pods using the VF
=> Bug OCPBUGS-2786: improve drain check

controllers/sriovnetworkpoolconfig_controller.go
=> OCPBUGS-4626: Fix machine config update in sriovnetworkpoolconfig_controller

controllers/sriovnetworkpoolconfig_controller.go
=> OCPBUGS-4140: Fix machine config update in sriovnetworkpoolconfig_controller

bindata/scripts/bf2-switch-mode.sh
This patch adds a new script called bf2-switch-mode.sh that allows the user to easily switch the BF2 between Network Interface Controller (NIC) and Data Processing Unit (DPU) modes. This is useful for optimizing the BF2 for different workloads.
Co-authored-by: Costin Gamenț <costin.gament@gmail.com>
Signed-off-by: Balazs Nemeth <bnemeth@redhat.com>
=> Add script to switch BF2 between NIC and DPU mode

controllers/sriovnetworkpoolconfig_controller.go
=> OCPBUGS-4390: Fix machine config update in sriovnetworkpoolconfig_controller

pkg/daemon/daemon.go
we need to add a drain context as it's used by the drain method.
crash log
```
I0214 14:14:35.597511   10742 daemon.go:932] drainNode(): Start draining
E0214 14:14:35.601267   10742 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 276 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2452ba0, 0x3ad55a0})
/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000dd6340})
/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x2452ba0, 0x3ad55a0}) …
```
=> OCPBUGS-7518: [release-4.10] add context to drain

bindata/manifests/switchdev-config/ovs-units/ovs-vswitchd.service.yaml, pkg/render/testdata/machineconfig/units/ovs-vswitchd.service.yaml
The "no-wait" argument is needed for ovs-vsctl commands because there is a chance for ovs-vsctl to timeout.
Adding "--no-wait" to the command line would make it such that ovs-vsctl doesn't wait for ovs-vswitchd to update "cur_cfg"
An example of this timeout is shown here:
ovs-vsctl[3265]: ovs|00001|vsctl|INFO|Called as /bin/ovs-vsctl set Open_vSwitch . other_config:hw-offload=true systemd[1]: ovs-vswitchd.service: start-pre operation timed out. Terminating. ovs-vsctl[3265]: 2023-02-22T22:00:20Z|00002|fatal_signal|WARN|terminating with signal 15 (Terminated) ovs-vsctl[3265]: ovs|00002|fatal_signal|WARN|terminating with signal 15 (Terminated) systemd[1]: ovs-vswitchd.service: Failed with result 'timeout'. systemd[1]: Failed to start Open vSwitch Forwarding Unit.
(cherry picked from commit …
=> [release-4.13] OCPBUGS-7856: Add the no-wait argument to ovs-vsctl commands for hw-offload

bindata/manifests/switchdev-config/ovs-units/ovs-vswitchd.service.yaml, pkg/render/testdata/machineconfig/units/ovs-vswitchd.service.yaml
The "no-wait" argument is needed for ovs-vsctl commands because there is a chance for ovs-vsctl to timeout.
Adding "--no-wait" to the command line would make it such that ovs-vsctl doesn't wait for ovs-vswitchd to update "cur_cfg"
An example of this timeout is shown here:
ovs-vsctl[3265]: ovs|00001|vsctl|INFO|Called as /bin/ovs-vsctl set Open_vSwitch . other_config:hw-offload=true systemd[1]: ovs-vswitchd.service: start-pre operation timed out. Terminating. ovs-vsctl[3265]: 2023-02-22T22:00:20Z|00002|fatal_signal|WARN|terminating with signal 15 (Terminated) ovs-vsctl[3265]: ovs|00002|fatal_signal|WARN|terminating with signal 15 (Terminated) systemd[1]: ovs-vswitchd.service: Failed with result 'timeout'. systemd[1]: Failed to start Open vSwitch Forwarding Unit.
(cherry picked from commit …
=> [release-4.12] OCPBUGS-10280: Add the no-wait argument to ovs-vsctl commands for hw-offload

test/util/network/network.go, test/util/network/network_test.go
Annotation `k8s.v1.cni.cncf.io/networks-status` has been changed to `k8s.v1.cni.cncf.io/network-status` and the former is no longer supported. Use the new key in e2e tests utilities.
Refs:
k8snetworkplumbingwg/network-attachment-definition-client/pull/45
=> OCPBUGS-11065: Fix networks-status annotation in e2e tests

pkg/plugins/generic/generic_plugin.go
Backport 'Fix drain logic after node reboot'[1]
After rebooting a node, CNI call to re-establish the secondary interface on a workload pod fails. Draining the node fixes this issue.
Fixes: [OCPBUGS-8105](https://issues.redhat.com/browse/OCPBUGS-8105)
[1] https://github.com/e0ne/sriov-network-operator/commit/5796b5d77b8efb8a2e6f1e209ffc27d3f1922063
=> OCPBUGS-8105: Fix drain logic after node reboot

pkg/plugins/generic/generic_plugin.go
Backport 'Fix drain logic after node reboot'[1]
After rebooting a node, CNI call to re-establish the secondary interface on a workload pod fails. Draining the node fixes this issue.
Fixes: [OCPBUGS-11170](https://issues.redhat.com/browse/OCPBUGS-11170)
[1] https://github.com/e0ne/sriov-network-operator/commit/5796b5d77b8efb8a2e6f1e209ffc27d3f1922063
=> OCPBUGS-11170: Fix drain logic after node reboot

pkg/daemon/daemon.go
we need to remove the Red Hat Virtio network device from the udev rule configuration if we don't remove it when running the config-daemon on a virtual node it will disconnect the node after a reboot even that the operator should not be installed on virtual environments that are not openstack we should not destroy the cluster if the operator is installed there
=> OCPBUGS-13284: Skip the Redhat virtual nic from udev rule

pkg/daemon/daemon.go
Backport the following commits:
- 'Continue node drain after reboot' d48291194e861bcbcb575b9884d6a0a7a615d461
- 'Annotate node only if there is no existing annotation' 008d2fe669e8922f783b43c490d7a5820bc55daa
After a node reboot, the number of VFs would be zero, then `reqDrain` would be set and we will need to drain also after a reboot. This behavior is caused by this
commit backport  https://github.com/openshift/sriov-network-operator/commit/7d099d32f3a38e89a56f73807ce60aa26b35cef4 . This will cause the drain lock to be attempted to be taken again. However a deadlock would occur if another node already took the lock at the same time. The  'Continue node drain after reboot' commit solves this issue by checking if we have the drain node annotation which means we are safe to proceed …
=> [release-4.10] OCPBUGS-14360: Continue node drain after reboot

bindata/scripts/bf2-switch-mode.sh
Currently if multiple devices are detected, bf2-switch-mode will fail, and provide the misleading error "Can't find bluefield device".
Instead, check each device to verify if it is a Bluefield2, and if so, apply new configurations.
=> OCPBUGS-14591: Allow for multiple devices

Dockerfile.sriov-network-config-daemon, Dockerfile.sriov-network-config-daemon.rhel7
Without pciutils, we will get the following error message when running mstfwreset:
Continue with reset?[y/N] y
Failed
-E- failed to run 'setpci -s 0000:c9:02.0 0x0.w'.
The setpci command is part of the pciutils package.
=> OCPBUGS-14154: Add pciutils dependency

pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
In OCP we have two steps to prepare a node before we drain it. first we get leader election and annotate the node with Draining and then we pause the MCP and mark the node as MCP paused.
if the config_daemon get a reset between the fist part to the second it will get stuck because one node will take the leader election BUT it will not mark the node as Draining as there is another node already draining. and the node with the draining label will try to get the drain lock again but the first node has it.
with this change if the node as Draning or MCP pause label it will not try to take the lock again and just continue after the reset.
=> OCPBUGS-16247: [release-4.13] Fix race condition in leader election for OCP

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, bundle/manifests/supported-nic-ids_v1_configmap.yaml, config/manifests/bases/sriov-network-operator_configmap.yaml, deploy/configmap.yaml, deployment/sriov-network-operator/templates/configmap.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml, pkg/webhook/validate_test.go
https://github.com/openshift/sriov-network-operator/pull/808 added support for Broadcom BCM57504. Since no vendor from Broadcom is currently participating in maintaining support for this card upstream, this change has been made downstream only.
In order to avoid future merge conflicts with u/s, this change should be added in d/s only files. This commit reverts any changes to u/s config maps.
=> Partially revert BCM57504 update

bindata/scripts/bf2-switch-mode.sh
Currently if multiple devices are detected, bf2-switch-mode will fail, and provide the misleading error "Can't find bluefield device".
Instead, check each device to verify if it is a Bluefield2, and if so, apply new configurations.
=> OCPBUGS-14954: Fix multiple dev bug 4.13

manifests/stable/supported-nic-ids_v1_configmap.yaml
Enable legacy SR-IOV in Broadcom BCM57504 NetXtreme-E device. Backport of:
https://github.com/openshift/sriov-network-operator/pull/808 https://github.com/openshift/sriov-network-operator/pull/809
=> OCPBUGS-17929: Add support for BCM57504 Release 4.13

hack/env.sh
This reverts commit 3eb2f83d98d091e48ba2ff3a8f83d86c5da004c6.
We should not use upstream images downstream as ds only resources will be missing when deploying with make deploy-setup. (i.e. /bindata/scripts/bf2-switch-mode.sh)
=> Revert "Updating images to pull from github instead of quay.io"

manifests/stable/supported-nic-ids_v1_configmap.yaml
Enable legacy SR-IOV in Broadcom BCM57504 NetXtreme-E device. Backport of:
https://github.com/openshift/sriov-network-operator/pull/808
https://github.com/openshift/sriov-network-operator/pull/809
=> OCPBUGS-17930: Add support for BCM57504 Release 4.12

api/v1/sriovnetworknodepolicy_types.go, bundle.Dockerfile, bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, bundle/manifests/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml, bundle/metadata/annotations.yaml, config/crd/bases/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml, controllers/sriovnetworknodepolicy_controller.go, controllers/sriovnetworknodepolicy_controller_test.go, deployment/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml, pkg/webhook/validate.go, pkg/webhook/validate_test.go, vendor/k8s.io/apimachinery/pkg/util/rand/rand.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Backport of
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/435
Adding 
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/422
to avoid conflicts
=> OCPBUGS-18409: [release-4.13] Allow creating policies that ignore NUMA topology

cmd/webhook/start.go, controllers/sriovnetworknodepolicy_controller.go, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go, pkg/plugins/k8s/k8s_plugin.go, pkg/render/render.go, pkg/service/service_manager.go, pkg/service/utils.go, pkg/systemd/systemd.go, pkg/utils/driver.go, pkg/utils/sriov.go, pkg/utils/utils.go, pkg/utils/utils_virtual.go, test/util/fakefilesystem/fakefilesystem.go, test/util/netns/netns.go
In case a policy specifying a different MTU, in the past, the MTU of the PF associated with the VFs would also be updated. Since reducing the MTU on PF could cause issues when the PF is used by other things too (i.e. primary network), reducing the MTU could cause connectivity issues. Therefore, take the conservative approach of never reducing the MTU on the PF when configuring the MTU on the VF.
=> OCPBUGS-16906: Never reduce MTU on PF

api/v1/helper.go, controllers/sriovnetworknodepolicy_controller.go, main.go, pkg/utils/utils.go
Backport of 
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/477
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/468
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/478
=> OCPBUGS-18451: [release-4.13] Reduce operator and config-daemon verbosity

pkg/utils/utils.go
In case a policy specifying a different MTU, in the past, the MTU of the PF associated with the VFs would also be updated. Since reducing the MTU on PF could cause issues when the PF is used by other things too (i.e. primary network), reducing the MTU could cause connectivity issues. Therefore, take the conservative approach of never reducing the MTU on the PF when configuring the MTU on the VF.
=> OCPBUGS-18501: SR-IOV should reject bad MTU config in policy

Makefile.bundle, bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/sriov-network-operator.package.yaml, manifests/stable/image-references, manifests/stable/sriov-network-operator.clusterserviceversion.yaml, pkg/version/version.go
updated references from 4.14 to 4.15 via:
```
find . -not -path "./vendor*" -type f -print0 | xargs -0 sed -i 's/4\.14/4.15/g'
make -f Makefile.bundle bundle
```
cc @wizhaoredhat, @bn222
=> OCPBUGS-20211: update version to 4.15

bundle/manifests/supported-nic-ids_v1_configmap.yaml, config/manifests/bases/sriov-network-operator_configmap.yaml, manifests/stable/supported-nic-ids_v1_configmap.yaml
For DPDK on virtualized environments, we need this device to be
supported.
This was added upstream but missed during a downstream sync because
these files are only for OpenShift.
Note that we already support RH Virtio network device. This new device
is for the recent versions of QEMU.
=> [downstream-only] Support RH Virtio 1.0 network device

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Since [image-references](https://github.com/openshift/sriov-network-operator/blob/master/manifests/stable/image-references) are configured by version for this repo.
=> Match origin image to configured image reference

controllers/sriovibnetwork_controller.go, controllers/sriovibnetwork_controller_test.go, controllers/sriovnetwork_controller.go, controllers/sriovnetwork_controller_test.go, controllers/suite_test.go, main.go
Backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/493
=> OCPBUGS-19440: [release-4.14]: SriovNetwork, SriovIBNetwork, react on namespace creation

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Since [image-references](https://github.com/openshift/sriov-network-operator/blob/release-4.14/manifests/stable/image-references) are configured by version for this repo.
=> OCPBUGS-22904: Match origin image to configured image reference

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Since [image-references](https://github.com/openshift/sriov-network-operator/blob/release-4.13/manifests/stable/image-references) are configured by version for this repo.
=> OCPBUGS-22905: Match origin image to configured image reference

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Since [image-references](https://github.com/openshift/sriov-network-operator/blob/release-4.12/manifests/stable/image-references) are configured by version for this repo.
=> OCPBUGS-22906: Match origin image to configured image reference

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Since [image-references](https://github.com/openshift/sriov-network-operator/blob/release-4.11/manifests/stable/image-references) are configured by version for this repo.
=> OCPBUGS-22907: Match origin image to configured image reference

bindata/manifests/daemon/daemonset.yaml
A downstream merge [1][2] overrode the annotations in the config daemonset. This resulted in he sriov-network-config-daemon pod missing the `target.workload.openshift.io/management` annotation which led to the pod not being pinned to the management cores when workload partitioning is enabled.
This is a downstream-only patch.
[1] https://github.com/openshift/sriov-network-operator/pull/868
[2] commit 0f177536b2db307af95d251548bd5c055e2b543c
=> OCPBUGS-24231: Fix config daemon annotation override

controllers/sriovibnetwork_controller.go, controllers/sriovibnetwork_controller_test.go, controllers/sriovnetwork_controller.go, controllers/sriovnetwork_controller_test.go, controllers/suite_test.go, main.go
4.12 Backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/493
=> OCPBUGS-25854: [release-4.12]: SriovNetwork, SriovIBNetwork, react on namespace creation

Makefile
Using `@latest` for tools dependecies produces unrepeatable builds which might break at any point in time. This is particularly important when maintaining released versions which need a backport fix.
Note: At the moment is not possible to reference the package `sigs.k8s.io/controller-runtime/tools/setup-envtest` with a specific version:
```
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.16.3: module sigs.k8s.io/controller-runtime@v0.16.3 found, but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest
```
See https://github.com/kubernetes-sigs/kubebuilder/issues/2480
Ref:
https://github.com/openshift/sriov-network-operator/pull/849
=> OCPBUGS-25924: envtest: Stick to a specific setup-envtest version

.gitignore, test/conformance/tests/test_sriov_operator.go, test/util/cluster/cluster.go
Backport of
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/596
and related E2E test fixes
cc @gregkopels
=> OCPBUGS-29473: [release-4.15] e2e: Skip tests when no VF-IO devices are available

Makefile.bundle
we need this because when we use the go install the version for the operator-sdk is unknown
=> download the operator-sdk instead of go install

main.go
There is no need to create default pool the operator handles that.
This was a left over on the feature parity backport
=> OCPBUGS-37585: Do not create default pool CR

pkg/helper/mock/mock_helper.go, pkg/host/internal/sriov/sriov.go, pkg/host/internal/sriov/sriov_test.go, pkg/host/store/mock/mock_store.go, pkg/host/store/store.go, pkg/plugins/mellanox/mellanox_plugin.go, test/conformance/tests/test_sriov_operator.go
4.16 Backport of
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/734
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/743
no conflicts
This should fix the failing test
```
[It] [sriov] operator Custom SriovNetworkNodePolicy ExternallyManaged Validation Should create a policy if the number of requested vfs is equal and not delete them when the policy is removed
```
cc @SchSeba
=> OCPBUGS-38010: [release-4.16]: Skip firmware reset on devices the operator doesn't control

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/rbac/role.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Make the operator create PrometheusRules to browse metrics in the Developer Console.
refs:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/732
=> d/s: CNF-12002 set `METRICS_EXPORTER_PROMETHEUS_DEPLOY_RULES`

pkg/utils/shutdown.go, test/conformance/tests/test_sriov_operator.go
4.17 Backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/760
=> OCPBUGS-37668: [release-4.17]: Fix operator quick restart for SNO

controllers/sriovnetworknodepolicy_controller.go
4.13 backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/487
=> OCPBUGS-42956: [release-4.13] Render SriovNetworkNodeState before Device Plugin ConfigMap

pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
When the operator changes the device-plugin Spec (e.g. .Spec.NodeSelector), it may happen that there are two device plugin pods for a given node, one that is terminating, the other that is initializing.
If the config-daemon executes `restartDevicePluginPod()` at the same time, it may kill the terminating pod, while the initializing one will run with the old dp configuration. This may cause one or more resources to not being advertised, until a manual device plugin restart occurs.
Make the config-daemon restart all the device-plugin instances it founds for its own node.
4.17 backport of 
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/783
=> OCPBUGS-43027: [release-4.17] config-daemon: Restart all instances of device-plugin

controllers/sriovoperatorconfig_controller.go, controllers/sriovoperatorconfig_controller_test.go, pkg/host/internal/network/network.go, pkg/host/internal/vdpa/vdpa.go
When a user deletes the default SriovOperatorConfig resource and tries to recreate it afterwards, the operator webhooks returns the error:
```
Error from server (InternalError): error when creating "/tmp/opconfig.yml": Internal error occurred: failed calling webhook "operator-webhook.sriovnetwork.openshift.io": failed to call webhook: Post "https://operator-webhook-service.openshift-sriov-network-operator.svc:443/validating-custom-resource?timeout=10s": service "operator-webhook-service" not found
```
as the webhook configuration is still present, while the Service and the DaemonSet has been deleted.
Delete all the webhook configurations when the user deletes the default SriovOperatorConfig
4.17 backport of
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/779
=> OCPBUGS-43108: [release-4.17] Delete webhooks when SriovOperatorConfig is deleted

controllers/generic_network_controller.go, controllers/sriovnetwork_controller_test.go
4.17 backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/775
=> OCPBUGS-42252: [release-4.17] Preserve user defined annotations on `SriovNetworks`

hack/env.sh
Currently, `make deploy-setup` fails unless we set `$SKIP_VAR_SET`.
Quote commit message:
---
hack/env.sh: fix detecting default values for images
Note that most of quay.io repositories (not all of them) are depublished
and the detection no longer works:
FATA[0001] Error parsing image name "docker://quay.io/openshift/origin-sriov-cni": reading manifest latest in quay.io/openshift/origin-sriov-cni: unauthorized: access to the requested resource is not authorized
Together that with [1],  the calling shell scripts now `set -e`, which
exits the script in such errors.
This means, `make deploy-setup` fails unless $SKIP_VAR_SET is set. That
is even if the caller *did* set the missing environment variables for
the images. Note that doing that is not useless, because while several
quay.io …
=> [th/deploy-detect-defaults] fix `make deploy-setup` to pass and autodetect some URLs

test/conformance/tests/test_exporter_metrics.go
release-4.17 backport of
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/785
`sriov_kubepoddevice` metric might end up in the Prometheus database after a while, as the default scrape interval is 30s. This leads to failures in the end-to-end lane like:
```
[sriov] Metrics Exporter When Prometheus operator is available [It] Metrics should have the correct labels
/root/opr-ocp2-1/data/sriov-network-operator/sriov-network-operator/test/conformance/tests/test_exporter_metrics.go:132
[FAILED] no value for metric sriov_kubepoddevice
```
Put the metric assertion in an `Eventually` statement
=> OCPBUGS-52306: [release-4.17] metrics: Fix `Metrics should have the correct labels` test

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/README.md, vendor/github.com/golang-jwt/jwt/v4/SECURITY.md, vendor/github.com/golang-jwt/jwt/v4/claims.go, vendor/github.com/golang-jwt/jwt/v4/errors.go, vendor/github.com/golang-jwt/jwt/v4/map_claims.go, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v4/parser_option.go, vendor/github.com/golang-jwt/jwt/v4/rsa_pss.go, vendor/github.com/golang-jwt/jwt/v4/token.go, vendor/github.com/golang-jwt/jwt/v4/types.go, vendor/modules.txt
CVE-2025-30204
```
update jwt entry manually in "go.mod" file to bump to fixed version 4.5.2
go mod download github.com/golang-jwt/jwt/v4
go mod vendor && go mod tidy
```
=> OCPBUGS-54085: [release-4.13] Bump github.com/golang-jwt/jwt/v4 from v4.2.0 to 4.5.2

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Following https://olm.operatorframework.io/docs/advanced-tasks/ship-operator-supporting-multiarch/ to add the ARM target architecture.
=> OCPBUGS-56215: Enable ARM architecture for the operator bundle

pkg/daemon/daemon.go
in case we have waiting for a drain and the user change the label in the node annotation manually it can make the configuration stuck as the daemon will not re-apply the right label to correct the user changes.
This will also help cover issue if exist in the draining logic in a way that the daemon will be able to retry again and not stuck waiting for a reconcile
=> OCPBUGS-59200: add requeue when we wait for drain to complete

pkg/consts/constants.go, pkg/daemon/plugin_test.go, pkg/plugins/generic/generic_plugin.go, pkg/plugins/generic/generic_plugin_test.go
The kernel argument `iommu.passthgouh` can break some GPU scenarios when set to `1` [1]:
>  We recommend that you add the iommu.passthrough=0 kernel parameter until this
issue is resolved
Avoid set the argument, as it would be hard for the user to undone the effect of this operation, as the config-daemon would reconcile the parameter list.
[1] https://docs.nvidia.com/grace-linux-install-guide.pdf
=> OCPBUGS-59290: [release-4.18] kernel: Avoid setting iommu.passthrough on ARM system

bundle/manifests/sriov-network-operator.clusterserviceversion.yaml, config/rbac/role.yaml, manifests/stable/sriov-network-operator.clusterserviceversion.yaml
This update introduces new rules in the RBAC configuration to allow the SR-IOV operator to manage network policies.
Needed for:
- https://github.com/openshift/sriov-network-operator/pull/1112
=> CNF-17884: Add RBAC permissions for network policies in SR-IOV operator
