openshift/sriov-network-operator

- README.md
Fix formatting of an header and make sure all resource sections
are on the same level.
> fix headers in README.md

- cmd/manager/main.go
- deploy/crds/sriovnetwork_v1_sriovnetworknodepolicy_crd.yaml
- pkg/apis/sriovnetwork/v1/sriovnetworknodepolicy_types.go
- pkg/apis/sriovnetwork/v1/zz_generated.openapi.go
> Adjust CR validation

- Dockerfile
- Dockerfile.rhel7
- Dockerfile.sriov-network-config-daemon
- Dockerfile.sriov-network-config-daemon.rhel7
- Makefile
- pkg/plugins/mellanox/mellanox_plugin.go
Change Mlnx devices link type to ETH if it is another type, change the total VFs to the requested num of VFs, disable SRIOV for Mlnx cards if the num of VFs is 0 otherwise enable it.
> Add mellanox plugin

- deploy/clusterrole.yaml
It needs the new roles for webhook deployment and other things.
> Add cluster roles required by the operator

- hack/build-go.sh
- hack/build-plugins.sh
per https://jira.coreos.com/browse/ART-666 (for FIPS enablement)
> build scripts: remove no_openssl

- Dockerfile.sriov-network-config-daemon
- Dockerfile.sriov-network-config-daemon.rhel7
> Install hwdata pacakge in config daemon image

- bindata/manifests/webhook/001-service.yaml
- bindata/manifests/webhook/server.yaml
> bind webhook to targetPort 6443

- manifests/4.2/sriov-network-operator.package.yaml
> Change package name to match the repo name

- bindata/scripts/enable-kargs.sh
- pkg/daemon/daemon.go
- pkg/plugins/generic/generic_plugin.go
> Fix kargs loading issue on RHCOS

- pkg/plugins/mellanox/mellanox_plugin.go
> Fix single port NICs bug for link type attribte

- pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1737780
> Update entire DaemonSet CR

- bindata/manifests/cni-config/sriov-cni-config.yaml
- deploy/crds/sriovnetwork.openshift.io_sriovnetworks_crd.yaml
- pkg/apis/sriovnetwork/v1/sriovnetwork_types.go
- pkg/apis/sriovnetwork/v1/zz_generated.openapi.go
- pkg/controller/sriovnetwork/sriovnetwork_controller.go
This is to support runtimeConfig for MAC
and IP address.
> add capabilities field in sriovnetwork

- pkg/webhook/mutate.go
Webhook shall patch both priority and deviceType if both are missing
> Bug 1771233: Webhook patch both priority and deviceType

- pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go
- pkg/daemon/daemon.go
- pkg/plugins/generic/generic_plugin.go
- pkg/utils/driver.go
- pkg/utils/utils.go
Only drain the node, when the number of VF is changed.
> Bug 1771984: Optimize node draining condition

- manifests/art.yaml
- manifests/sriov-network-operator.package.yaml
> Bump version to 4.4 for operator bundle

- pkg/apis/sriovnetwork/v1/helper.go
Reverts openshift/sriov-network-operator#149
> Revert "BUG 1798886: Allow user to set vf range to '0-0'"

- pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go
Not delete the daemonset of device and cni plugins, when the last node policy is
deleted. Instead, set a nodeselector matching no node to the daemonsets.
This is to prevent the satuation that the node draining try to delete the plugin pod
which has already in 'Terminating' state. Sometimes, it may make the pod stuck in
'Terminating' for a very long time.
> BUG 1800426: Not delete the daemonset of device and cni plugins, delete the pods instead

- cmd/sriov-network-config-daemon/start.go
- pkg/daemon/daemon.go
- pkg/utils/driver.go
- pkg/utils/utils.go
Check whether desired state is the same as the current one before
executing.
> [release-4.3] BUG 1798344: Optimize VF configure logic

- pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go
- pkg/controller/sriovoperatorconfig/sriovoperatorconfig_controller.go
Namespace is a global variable retireved from
environment variable, the change avoid getting
Namespace from env var multiple times.
> use Namespace from global variable

- bindata/manifests/cni-config/sriov-cni-config.yaml
- test/e2e/e2e_test.go
This will reflected in the network status annotation of each pod.
> Replace the hardcoded CNI network name (sriov-net) with Network Name from SR-IOV network

- cmd/manager/main.go
- deploy/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies_crd.yaml
- manifests/4.5/sriov-network-operator-sriovnetwork.crd.yaml
- manifests/4.5/sriov-network-operator-sriovnetworknodepolicy.crd.yaml
- manifests/4.5/sriov-network-operator-sriovnetworknodestate.crd.yaml
- manifests/4.5/sriov-network-operator-sriovoperatorconfig.crd.yaml
- pkg/apis/sriovnetwork/v1/sriovnetworknodepolicy_types.go
Reverts openshift/sriov-network-operator#166
> Revert "Bug 1814919: Prevent user from setting numVfs to '0'"

- OWNERS
Probably doesn't make sense to ping me for every single PR :-)
> remove squeed from reviewers

- pkg/utils/driver.go
> Raising a meaningful error message if iommu is not enabled in bios

- test/conformance/tests/sriov_operator.go
- test/util/cluster/cluster.go
- test/util/pod/pod.go
This commit introduces a new waiting method.
We go over the logs from the config-daemon and wait for it to report the config generation as succeded.
> Make tests more stable

- test/util/cluster/cluster.go
This Commit is base on https://github.com/openshift/sriov-network-operator/pull/175
> Bug 1834371: Change the logs search in the test

- test/conformance/tests/sriov_operator.go
Since we look for nodes to be schedulable and sriov daemon's logs, depending on
the environment this could take more than 10 minutes.
That's amplified by the issue described in https://github.com/openshift/sriov-network-operator/pull/200
This PR makes the waiting time (even) longer and also configurable.
Also, comment overlapping ranges test as it's always skipped as of today.
> Bug 1836149: Make it possible to configure the cluster waiting timeout.

- test/conformance/tests/sriov_operator.go
- test/conformance/tests/vfs_assignement.go
- test/util/cluster/cluster.go
This should make the tests match both 4.4 and 4.5 versions.
> Bug 1836912: Make the tests work on both 4.5 and 4.4 cluster.

- pkg/daemon/daemon.go
When the get nodes in uncordon fails, the daemon exits and the node remains uncordoned.
When the get of the device plugin pod fails, the daemon does not restart it and the
change requested does not get applied.
This is a manual cherry pick of https://github.com/openshift/sriov-network-operator/pull/222
> Bug 1841042: [Release 4.4] Make the daemon more resilient to failures.

- pkg/utils/utils.go
PF: Mac address and linkSpeed
VF: Mac address and name
> Get more info about PFs and VFs

- test/conformance/tests/sriov_operator.go
Added new test connectivity when PF in down.
> Test case Unhealthy VFs removed due to obsolescence in 4.4.

- test/conformance/tests/sriov_operator.go
> Fix sriov for test to use new k8s client

- pkg/apis/sriovnetwork/v1/helper.go
- pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go
PF configs may affect how VF works, for example:
If VF mtu is set to a value larger than PF mtu, application
will not benefit from large mtu size configured for VF. This
happens when SR-IOV partition is configured with different mtu
sizes.
This commit also uses large numVfs in SR-IOV partition case.
> partition: merge PF configs

- pkg/utils/utils.go
By default Mellanox InfiniBand links are initinialized with a zeroed
node and port GUID To perform RDMA traffic with RDMA CM needs to
initialize node and port GUID
> Generate random node and port guid for IB VFs for un-initialized VFs

- cmd/sriov-network-config-daemon/start.go
- go.mod
- go.sum
- hack/run-test.sh
- hack/undeploy.sh
- pkg/daemon/daemon.go
- pkg/daemon/writer.go
- pkg/plugins/generic/generic_plugin.go
- test/e2e/sriovoperatornodepolicy_test.go
Use work queue to store update request, retry when any sync error happen
> Not exit config daemon when sync failed

- pkg/webhook/validate.go
- pkg/webhook/validate_test.go
Webhook validation against policy may be inaccurate
when previous defined poilcies are not yet converted to
SriovNetworkNodeState.
> Webhook respect unapplied policy

- pkg/plugins/generic/generic_plugin.go
when SR-IOV policy is patched with mtu change only, generic
plugin shall promot needDrain flag
> generic plugin: drain node when mtu changes

- test/conformance/tests/sriov_operator.go
PR based on @mmirecki  https://github.com/openshift/sriov-network-operator/pull/201
> Added new test Webhook resource injector

- test/conformance/tests/sriov_operator.go
This commint remove a duplicate test that was introduce in a rebase.
> Remove a deplicate test

- test/conformance/tests/sriov_operator.go
This comment add a nic validation functional test.
> Add a nic test validation

- cmd/sriov-network-config-daemon/start.go
- pkg/daemon/writer.go
- pkg/utils/utils.go
1. When reseting PF MTU, the daemon reset it to actual initial value.
2. When setting MTU, the daemon always set the MTU of VF to the desired value.
3. Set the VF MTU to PF's if MTU is not provided by users.
> [release-4.5] BUG 1854778: Improve the MTU set/reset logic

- cmd/sriov-network-config-daemon/start.go
- pkg/daemon/writer.go
- pkg/utils/utils.go
1. When reseting PF MTU, the daemon reset it to actual initial value.
2. When setting MTU, the daemon always set the MTU of VF to the desired value.
3. Set the VF MTU to PF's if MTU is not provided by users.
> [release-4.4] BUG 1854779: Improve the MTU set/reset logic

- pkg/utils/utils.go
VF link may not be immediately ready after VF creation.
> BUG 1853785: Retry for VF link to become ready

- test/util/cluster/cluster.go
This commit update the log search
> Update the log seach for tests

- test/conformance/tests/sriov_operator.go
- test/util/cluster/cluster.go
The PR is a temporary fix for an issue experienced in test runs.
The issue occurs very sporadically and as such is difficult to debug properly.
It seems that once every few hundred runs an EOF error is returned without a valid reason (or so it seems).
> Bug 1876822: Workaround for unexpected EOF during node state lookup

- test/util/cluster/cluster.go
There commit remove the log verification in the test.
This check make many issues in the tests and we don't need it any more.
It was introduce to validate the policy is applied but the update status
work as expected.
we also have a resource validation after that because it can take sometime
for the device plugin to report the resources to the kubelet.
> Bug 1880990: Remove the log verification

- test/conformance/tests/sriov_operator.go
Here we use another approach to see if the interface is slave of the bridge.
Also, this test proved itself to be pretty dangerous, disabling it in
discovery mode.
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
> Bug 1880990: Fix PF shutdown test. On some nodes route link returns void.

- pkg/utils/utils.go
- test/util/cluster/cluster.go
This commit adds a workaround for the BZ
https://bugzilla.redhat.com/show_bug.cgi?id=1875338
In the commit we try to get the interface name from the PCI address
if the PCI address doesn't exist after 10 sec we unbind the VF
and return an error to the queue so the daemon can reconcile on it
again.
Base on https://github.com/openshift/sriov-network-operator/pull/345
> Bug 1883559: Retry on driver error

- .gitignore
Signed-off-by: Alexey Roytman <roytman@il.ibm.com>
> Add GoLand IDE files to .gitignore

- Makefile
> Fix failure deploying operator on Ubuntu

- controllers/sriovnetworknodepolicy_controller.go
The networkpolicy controller is configured so that daemonsets / sriov network status are subresources of the policy. What happens is that whenever a policy is added, the controller goes into an endless loop where it updates the subresources and get notified of those changes through the primary one (the policy), and then updates again and so on.
This can be seen looking at the operator's logs (I noticed it by chance running the operator locally).
If the subresources' specs do not change from what's read from the api we don't update them, stopping the loop.
> Don't update the daemonsets / the network status if there are no changes

- api/v1/helper.go
- api/v1/helper_test.go
- api/v1/testdata/TestIBRendering/simpleib.golden
- api/v1/testdata/TestRendering/chained.golden
- api/v1/testdata/TestRendering/simple.golden
The template now has a MetaPluginsConfigured plugin that is not set in case of infiniband. We set it to false as we don't expect metaplugins to be needed in case of ib.
> Fix infiniband rendering

- test/conformance/tests/sriov_operator.go
We want to make sure that the pf can be used on host level, even if pf is used by a pod.
> Conformance tests: add a test that runs a pod with a vf from the primary pf.

- test/util/cluster/cluster.go
Currently the tests use a duplicated list,
changed to use the function supplied by the api
cherry-pick from https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/68
> Use the function in the api to validate if a device is supported

- pkg/apis/sriovnetwork/v1/helper.go
> Bug 1951864: Add Intel XXV710 NIC model (1572)

- Makefile
- PROJECT
- deployment/sriov-network-operator/templates/clusterrole.yaml
- deployment/sriov-network-operator/templates/clusterrolebinding.yaml
- hack/deploy-wait.sh
- hack/run-e2e-conformance.sh
- hack/undeploy.sh
- test/conformance/tests/sriov_operator.go
- test/util/client/clients.go
- test/validation/test_suite_test.go
- test/validation/tests/validation.go
This syncs with upstream, adding a validation suite useful for CI
> Bug 1964847: Sync 26-05-21 - add validation test suite

- Makefile
- pkg/utils/utils.go
> Bug 1958467: Fix index out of range panic when ifaceName is empty

- pkg/plugins/mellanox/mellanox_plugin.go
- pkg/utils/utils.go
Fix kernel lockdown checking in chroot
https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/137
> Bug 1961854: Fix kernel lockdown checking in chroot

- pkg/utils/utils.go
> Bug 1958468: Fix index out of range panic when ifaceName is empty

- bindata/manifests/daemon/daemonset.yaml
- bindata/manifests/operator-webhook/server.yaml
- bindata/manifests/plugins/sriov-cni.yaml
- bindata/manifests/plugins/sriov-device-plugin.yaml
- bindata/manifests/webhook/server.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1958107
> Bug 1958107: Run SR-IOV pods in burstable QoS

- bindata/manifests/daemon/daemonset.yaml
- bindata/manifests/operator-webhook/server.yaml
- bindata/manifests/plugins/sriov-cni.yaml
- bindata/manifests/plugins/sriov-device-plugin.yaml
- bindata/manifests/webhook/server.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1960574
> Bug 1960574: Add priority class to SR-IOV daemonsets

- bindata/manifests/daemon/daemonset.yaml
- bindata/manifests/operator-webhook/server.yaml
- bindata/manifests/plugins/sriov-cni.yaml
- bindata/manifests/plugins/sriov-device-plugin.yaml
- bindata/manifests/webhook/server.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1957761
> Bug 1957761: Set update-strategy maxUnavailable for sriov daemonsets and deployments

- test/util/cluster/cluster.go
- test/util/pod/pod.go
This commit fix the functional tests when running on a secure boot environment
> Bug 1975216: Fix sriov functional tests for secure boot env

- bindata/manifests/operator-webhook/003-webhook.yaml
- bindata/manifests/webhook/003-webhook.yaml
- controllers/sriovoperatorconfig_controller.go
Sync content of MutatingWebhookConfiguration and ValidatingWebhookConfiguration
CRs when needed.
> [Release-4.8] Bug 1977540: Update Webhook Configuration objects when Reconciling

- manifests/4.9/sriov-network-operator.v4.9.0.clusterserviceversion.yaml
This was incorrectly being set in the spec.labels.
> Bug 1978435: Add labels to indicate availability of this operator for ppc64le

- manifests/4.8/sriov-network-operator.v4.8.0.clusterserviceversion.yaml
This was incorrectly set in spec.labels
> Bug 1978437: Add labels to indicate availability of this operator for ppc64le

- pkg/apis/sriovnetwork/v1/helper.go
> Bug 1958278: Enable E810 device IDs

- manifests/4.10/supported-nic-ids_v1_configmap.yaml
> Add Nvidia device ID 15b3/101f/101e

- manifests/4.9/supported-nic-ids_v1_configmap.yaml
> Bug 2026814: add Nvidia device ID 15b3/101f/101e

- manifests/4.10/supported-nic-ids_v1_configmap.yaml
> Add Pensando device ID 1dd8/1002/1003

- pkg/daemon/daemon.go
(cherry picked from commit 59cbb8b61bdba2b8cb5c2f260cf06913f5ef31ba)
> Bug 2028256: Check if generic_plugin is loaded before invoking it

- pkg/daemon/daemon.go
(cherry picked from commit 59cbb8b61bdba2b8cb5c2f260cf06913f5ef31ba)
> Bug 2028257: Check if generic_plugin is loaded before invoking it

- Dockerfile.rhel7
> Bump sriov operator image to ocp 4.11

- must-gather/Dockerfile.rhel7
there is no oc command inside the base container so we need to use the cli container
> Fix must-gather container

- cmd/sriov-network-config-daemon/start.go
- deploy/configmap.yaml
- deployment/sriov-network-operator/templates/configmap.yaml
- manifests/stable/supported-nic-ids_v1_configmap.yaml
- pkg/daemon/daemon.go
- pkg/daemon/writer.go
- pkg/utils/utils.go
- pkg/utils/utils_virtual.go
- pkg/webhook/validate.go
- Improve the virtual plugin support
- Fix the validation webhook for virtual environments
- Don't run the networkManager udev rule on virtual environments
> Bug 2036948: improve the virtual plugin support

- .github/workflows/go.yml
- Makefile
- bindata/scripts/enable-kargs.sh
- test/scripts/enable-kargs_test.sh
- test/scripts/rpm-ostree_mock
- test/scripts/shunit2
Close https://github.com/openshift/sriov-network-operator/issues/647
> Bug 2070888: Use /run/ostree-booted to determine RHCOS 

- pkg/webhook/validate_test.go
This reverts commit 7316cd03963f1b9e9cc8be5d1c9298269b161099.
> Bug 2087084: Revert "Add support for Pensando DSC card"

- test/conformance/tests/sriov_operator.go
This PR to bring test fix to [cnf-tests](https://github.com/openshift-kni/cnf-features-deploy)
> Update sysctl to a safe one in metapluging chaining test

- must-gather/collection-scripts/gather
Changes in this commit comes from
https://github.com/openshift/must-gather/ ,
as the collect script has been moved there
since release-4.11
Signed-off-by: Andrea Panattoni <apanatto@redhat.com>
> OCPBUGS-532: Backport must-gather improvements

- deploy/configmap.yaml
- deployment/sriov-network-operator/templates/configmap.yaml
This duplication was added in:
Commit: dd6f2efe221f8c3fde067df5d8d30c297089d06f
PR: https://github.com/openshift/sriov-network-operator/pull/681
> Remove duplicated Intel E810 NIC card

- test/conformance/tests/sriov_operator.go
This fix has been backported in 4.11 with:
- https://github.com/openshift/sriov-network-operator/pull/688
and fixes cnf-tests test
`[sriov] operator Generic SriovNetworkNodePolicy Virtual Functions should release the VFs once the pod deleted and same VFs can be used by the new created pods`
```
/remote-source/app/vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:837
Timed out after 120.003s.
Error to detect Required Event
Expected
<string>: failed to ensurePod sriov-conformance-testing/testpod-bb6nm since it is not yet scheduled
to contain substring
<string>: Insufficient openshift.io/testresource
/remote-source/app/vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go:892
```
> OCPBUGS-1888: Fixed sriov conformance release vf test case

- controllers/sriovnetworkpoolconfig_controller.go
> OCPBUGS-4391: Fix machine config update in sriovnetworkpoolconfig_controller

- controllers/sriovnetworkpoolconfig_controller.go
> OCPBUGS-4392: Fix machine config update in sriovnetworkpoolconfig_controller

- bundle/manifests/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
- bundle/manifests/sriovnetwork.openshift.io_sriovnetworknodestates.yaml
- manifests/stable/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
- manifests/stable/sriovnetwork.openshift.io_sriovnetworknodestates.yaml
See https://issues.redhat.com/browse/OCPBUGS-10381
> Fix bundle & manifest generation for vDPA CRDs

- api/v1/sriovnetworknodepolicy_types.go
- config/crd/bases/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
- controllers/sriovnetworknodepolicy_controller.go
- controllers/sriovnetworknodepolicy_controller_test.go
- deployment/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
- deployment/sriov-network-operator/values.yaml
- pkg/webhook/validate.go
- pkg/webhook/validate_test.go
- test/conformance/tests/test_sriov_operator.go
- vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Cherry-pick with no conflicts
```
git cherry-pick a46193341cd0665ea736aec3d1506f9058632367 \
bd6efc0380f6415f106eeda9e797a410edafb35b \
d34800e4eb1a38552c24674d7cc2070a55cd86b6 \
2ce10eaaf4838073ce89b607c6e5bdc23a22e9f5 \
f55a17e111bf31f64aabe382950ead94c1ed161a \
27f69740d30720b0ed6ed452b5111987bae1950a
```
> Downstream Sync 06-05

- pkg/daemon/daemon.go
we need to remove the Red Hat Virtio network device from the udev rule configuration if we don't remove it when running the config-daemon on a virtual node it will disconnect the node after a reboot even that the operator should not be installed on virtual environments that are not openstack we should not destroy the cluster if the operator is installed there
(cherry picked from commit fe32cadb9580ae3e205cdf63f8905c31f669b253) 
Conflicts:
There was refactoring done in the commit d20be75f5b92e2b4db155469d324cf837dd41ae2
under the PR 688 which caused some conflicts. However we should just
use the variable name "new_content" for this small backport.
> [release-4.10] OCPBUGS-14359: Skip the Redhat virtual nic from udev rule

- api/v1/helper.go
- controllers/sriovnetworknodepolicy_controller.go
- main.go
- test/conformance/tests/test_sriov_operator.go
- test/util/client/clients.go
> Downstream Sync 2023-08-04

- controllers/sriovnetworknodepolicy_controller.go
- pkg/utils/utils.go
> OCPBUGS-14499: Sync 20230811

- bundle/manifests/supported-nic-ids_v1_configmap.yaml
- config/manifests/bases/sriov-network-operator_configmap.yaml
- deploy/configmap.yaml
- deployment/sriov-network-operator/templates/configmap.yaml
- doc/supported-hardware.md
- manifests/stable/supported-nic-ids_v1_configmap.yaml
- pkg/daemon/daemon.go
- pkg/utils/testdata/meta_data.json
- pkg/utils/testdata/network_data.json
- pkg/utils/utils_virtual.go
- pkg/utils/utils_virtual_test.go
> OCPBUGS-22279: [release-4.14] virtual: get real PCI address for each device found

- test/util/cluster/cluster.go
- test/util/cluster/cluster_test.go
Backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/514
> OCPBUGS-25794: [release-4.14] conformance-test: Filter NIC by environment variable

- OWNERS
This might help with merging/reviewing downstream PR. e.g.
- https://github.com/openshift/release/pull/54079
> d/s: update owners

- hack/deploy-sriov-in-telco-ci.sh
this is a d/s only script that should be used
as part of the telco CI prow lane
it build container images from the PR and
push them together with the bunble and index
to the internal cluster registry.
> d/s only: deploy operator from pull request

- pkg/utils/shutdown.go
- test/conformance/tests/test_sriov_operator.go
Downstream sync PR via `git merge`. Relevant commit is:
- 1183e4f40949ef7ad05007e4e6abe424a1c9ed1d
All other commits appears here because the previous sync had modified the history:
- https://github.com/openshift/sriov-network-operator/pull/990
> OCPBUGS-23795: Downstream merge Sync/20240822

- bindata/manifests/daemon/daemonset.yaml
- bindata/manifests/operator-webhook/server.yaml
- bindata/manifests/webhook/server.yaml
- bundle/manifests/sriov-network-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/operator.yaml
- deployment/sriov-network-operator/templates/operator.yaml
- manifests/stable/sriov-network-operator.clusterserviceversion.yaml
[OCPBUGS-39502](https://issues.redhat.com//browse/OCPBUGS-39502)
Manual cherry-pick of #995
> [release-4.16] OCPBUGS-39502: SCC-pinning for openshift workloads

- pkg/webhook/validate.go
- pkg/webhook/validate_test.go
we allow any name for the pool policy
> OCPBUGS-39355: release[4.16] allow to remove a sriovPool named default

- controllers/sriovoperatorconfig_controller.go
- controllers/sriovoperatorconfig_controller_test.go
4.18 backport of
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/878
> OCPBUGS-54958: [release-4.18]: controllers: Use patch to add finalizers

- Makefile.bundle
- bundle/manifests/sriov-network-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/sriov-network-operator.clusterserviceversion.yaml
- manifests/sriov-network-operator.package.yaml
- manifests/stable/image-references
- manifests/stable/sriov-network-operator.clusterserviceversion.yaml
- pkg/version/version.go
> ds: bump operator to 4.20

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_linux.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_other.go
- vendor/github.com/golang/glog/glog_file_posix.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/github.com/golang/glog/glog_flags.go
- vendor/github.com/golang/glog/internal/logsink/logsink.go
- vendor/modules.txt
> OCPBUGS-58827,OCPBUGS-58819: Bump glog dependency to v1.2.4 that fixes CVE-2024-45339

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_linux.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_other.go
- vendor/github.com/golang/glog/glog_file_posix.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/github.com/golang/glog/glog_flags.go
- vendor/github.com/golang/glog/internal/logsink/logsink.go
- vendor/modules.txt
Bump glog dependency to v1.2.4 that fixes CVE-2024-45339
> OCPBUGS-58815,OCPBUGS-58823: Bump glog dependency to v1.2.4 that fixes CVE-2024-45339

- Makefile.bundle
- PROJECT
- bundle.Dockerfile
- bundle/manifests/operator-allow-egress-to-api-server_networking.k8s.io_v1_networkpolicy.yaml
- bundle/manifests/sriov-network-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/default/kustomization.yaml
- config/networkpolicies/allow_egress_api_server.yaml
- config/networkpolicies/kustomization.yaml
- manifests/stable/operator-allow-egress-to-api-server_networking.k8s.io_v1_networkpolicy.yaml
- manifests/stable/sriov-network-operator.clusterserviceversion.yaml
Operator's network policies added to the bundle
> CNF-17884 Operator's network policies

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_linux.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_other.go
- vendor/github.com/golang/glog/glog_file_posix.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/github.com/golang/glog/glog_flags.go
- vendor/github.com/golang/glog/internal/logsink/logsink.go
- vendor/modules.txt
Bump glog dependency to v1.2.4 that fixes CVE-2024-45339
> OCPBUGS-58816,OCPBUGS-58824: Bump glog dependency to v1.2.4 that fixes CVE-2024-45339

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_linux.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_other.go
- vendor/github.com/golang/glog/glog_file_posix.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/github.com/golang/glog/glog_flags.go
- vendor/github.com/golang/glog/internal/logsink/logsink.go
- vendor/github.com/golang/glog/internal/logsink/logsink_fatal.go
- vendor/github.com/golang/glog/internal/stackdump/stackdump.go
- vendor/modules.txt
Bump glog dependency to v1.2.4 that fixes CVE-2024-45339
> [release-4.13] OCPBUGS-59129,OCPBUGS-59130: Bump glog dependency to v1.2.4 that fixes CVE-2024-45339
